format = "$username$hostname$directory$git_branch$git_commit$git_state$git_status$kubernetes$aws$gcloud$line_break$character"

[aws]
format = "\\[[aws:($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"

[gcloud]
disabled = true
format = "\\[[gcp:$project(\\($region\\))]($style)\\]"

[git_branch]
format = "\\[[$symbol$branch]($style)\\]"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[kubernetes]
disabled = false
format = "\\[[kube:$context(\\($namespace\\))]($style)\\]"
