[tools]
"github:git-town/git-town" = "latest"
"github:psviderski/uncloud" = "latest"
"github:usagi-flow/evil-helix" = "latest"
buf = "latest"
bun = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
kubectl = "latest"
rg = "latest"
sd = "latest"
zoxide = "latest"
yq = "latest"
opencode = "latest"
